name: 'artifacts cleanup'
on:
  schedule:
    - cron: '0 15 * * *' # 毎日0時（UTC 15:00 = JST 00:00）に実行
  workflow_dispatch: # 手動実行も可能

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: '*' # 全部対象
