name: 'artifacts cleanup'
on:
  schedule:
    - cron: '0 0 * * *' # 毎日0時（UTC）に実行
  workflow_dispatch: # 手動実行も可能

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v4
        with:
          name: '*' # 全部対象
