name: CI

env:
  NODE_VERSION: '22.12.0'
  PNPM_VERSION: '9.15.9'

on:
  push:
    branches:
      - main
    paths: &PATHS
      - 'app/**'
      - '__e2e__'
      - '.storybook'
      - 'public'
      - 'test'
      - 'components.json'
      - '.lighthouserc.yml'
      - 'eslint.config.mjs'
      - 'playwright.config.ts'
      - 'react-router.config.ts'
      - 'tsconfig.json'
      - 'vite-plugin-remove-data-testid.ts'
      - 'vite.config.ts'
      - 'wrangler.jsonc'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths: *PATHS

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # node_modules のキャッシュを行わないため不要、一応残しておく
  # setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}

  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v4
  #       with:
  #         version: ${{ env.PNPM_VERSION }}
  #         run_install: true

  # - name: Save node_modules as artifact
  #   uses: actions/upload-artifact@v4
  #   with:
  #     name: node_modules
  #     path: node_modules
  #     retention-days: 1

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      # - name: Download node_modules artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: node_modules
      #     path: node_modules

      - name: Run lint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      # - name: Download node_modules artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: node_modules
      #     path: node_modules

      - name: Run tests
        run: pnpm test

  tsc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      # - name: Download node_modules artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: node_modules
      #     path: node_modules

      - name: Run TypeScript check
        run: pnpm tsc

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      # - name: Download node_modules artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: node_modules
      #     path: node_modules

      - name: Build project
        run: pnpm build

  test-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      # - name: Download node_modules artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: node_modules
      #     path: node_modules

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Storybook tests
        run: pnpm test-storybook

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      # - name: Download node_modules artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: node_modules
      #     path: node_modules

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: pnpm test:e2e

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      # - name: Download node_modules artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: node_modules
      #     path: node_modules

      - name: Run security audit
        run: pnpm audit --audit-level=moderate

  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      # - name: Download node_modules artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: node_modules
      #     path: node_modules

      - name: Check code formatting
        run: pnpm prettier --check

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      # - name: Download node_modules artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: node_modules
      #     path: node_modules

      - name: Run Lighthouse and assertion results
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: './.lighthouserc.yml'

  # https://blog.chick-p.work/blog/github-actions-workflow-deploy-cf-wokers
  deploy:
    runs-on: ubuntu-latest
    needs:
      [
        lint,
        build,
        test,
        tsc,
        test-storybook,
        e2e-test,
        security-audit,
        format-check,
        lighthouse,
      ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      - name: Build project
        run: pnpm build

      - name: Mask secrets
        run: echo "::add-mask::${{ secrets.CF_WORKERS_URL }}"

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          # default の 3.90.0 だと wrangler.toml しか受け付けないため明示指定
          wranglerVersion: '4.32.0'
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}

  delete-artifacts:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: geekyeggo/delete-artifact@v4
        with:
          name: '*' # 全部対象
