name: 'lighthouse'

env:
  NODE_VERSION: '22.12.0'
  PNPM_VERSION: '9.15.9'

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lighthouse.yml'
      - '.lighthouserc.yml'
  schedule:
    - cron: '0 0 * * 5' # 金曜0時（曜日=[0-6]、UTC 00:00 = JST 09:00）に実行
  workflow_dispatch: # 手動実行も可能

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Lighthouse and assertion results
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: './.lighthouserc.yml'
